"""Utilities for cleaning generated ALT text."""


def clean_alt_text(text: str) -> str:
    """Normalize ALT text output by removing vague prefixes and repairing leads.

    The cleaning logic trims whitespace, strips common prefixes like
    "this image shows", and capitalizes the first letter. It also attempts a
    small repair for sentences that start with "with text related to".

    Args:
        text: Raw ALT text generated by the model.

    Returns:
        str: Cleaned ALT text string.
    """
    raw = text.strip()
    raw_lower = raw.lower()

    removal_prefixes = [
        "this image shows",
        "this image displays",
        "the image displays",
        "the image shows",
        "the image appears to be",
        "the image presents a slide",
        "appears to be",
        "this slide shows",
        "this is a slide of",
        "a slide",
        "the image is a slide from a presentation",
        "the image is an educational slide",
        "the image is a presentation slide",
        "the image presents a slide from a presentation",
        "the image presents a slide from a lecture",
    ]

    text_lower = raw_lower
    for prefix in removal_prefixes:
        if text_lower.startswith(prefix):
            raw = raw[len(prefix):].lstrip(" ,.-")
            break
    
    #Fix awkward leads
    if raw.lower().startswith("with text related to"):
        raw = "Educational diagram related to " + raw[len("with text related to"):].lstrip(" .")

    #Normalize case
    return raw[0].upper() + raw[1:] if raw else raw
